# Generated by Django 4.0.1 on 2022-01-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_alter_primertabla_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primertabla',
            name='edit',
        ),
        migrations.AddField(
            model_name='primertabla',
            name='edited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
